//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSessionPresence
    {
        public int Id { get; set; }
        public int SessionId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime Date { get; set; }
        public string Remark { get; set; }
    
        public virtual CourseSession CourseSession { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
