//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCourseSessionPresence
    {
        public int CourseId { get; set; }
        public int EmployeeId { get; set; }
        public int SessionId { get; set; }
        public Nullable<int> PresenceId { get; set; }
        public Nullable<System.DateTime> SessionStart { get; set; }
        public Nullable<System.DateTime> SessionEnd { get; set; }
        public bool Done { get; set; }
        public string SessionRemark { get; set; }
        public string DayName { get; set; }
        public Nullable<int> Year { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> Month { get; set; }
        public string PDate { get; set; }
        public string PYearName { get; set; }
        public Nullable<int> PYear { get; set; }
        public string PMonthName { get; set; }
        public Nullable<int> PMonth { get; set; }
        public string PDayName { get; set; }
        public string No { get; set; }
        public string Instructor { get; set; }
        public string Title { get; set; }
        public string CT_Title { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public string Organization { get; set; }
        public Nullable<bool> IsGeneral { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Status { get; set; }
        public string PID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string JobGroupRoot { get; set; }
        public string NID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int SexId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string IDNo { get; set; }
        public string UserId { get; set; }
        public string Sex { get; set; }
        public int PersonId { get; set; }
        public Nullable<bool> InActive { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<System.DateTime> PresenceDate { get; set; }
        public string PresenceRemark { get; set; }
    }
}
